
##子夜
## github地址 https://github.com/6Svip120apk69
## TG频道地址 https://t.me/ziyescript
## TG交流群 https://t.me/joinchat/AAAAAE7XHm-q1-7Np-tF3g
## boxjs链接 https://raw.githubusercontent.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE/main/Task/ziye.boxjs.json


# #新建一个库，此文件路径为 .github/workflows/ziye-sync.yml 打开教程链接 https://www.jianshu.com/p/bb82b3ad1d11 ，申请PAT（找到时全部勾选），设置------secrets------新建仓库secret------namePAT值填写PAT的值        

##点击动作 手动运行或者等待定时运行可以自动生成分支 ZIYE 且自动同步文件至此

##其他作者库同理替换为    
 
##作者名 6Svip120apk69  
##作者库名 gitee_q8qsTAUA_cThxc1RBVUE     
##作者分支名主要     
# # 同步名 ZIYE （可自定义）




名称：子野同步
上：
  时间表：
    - cron：' 1 */3 * * * '
  工作流调度：
  观看：
    类型：开始
  存储库调度：
    类型：sync-6Svip120apk69-gitee_q8qsTAUA_cThxc1RBVUE
工作：
  回购同步：
    环境：
      PAT : ${{ 秘密.PAT }}
    运行：ubuntu-latest
    如果：github.event.repository.owner.id == github.event.sender.id
    步骤：
      -使用：actions/checkout@v2
        与：
          持久凭证：假

      -名称：同步 6Svip120apk69-gitee_q8qsTAUA_cThxc1RBVUE
        用途：repo-sync/github-sync@v2
        如果：env.PAT
        与：
          source_repo：“ https://github.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE.git ”
          源分支：“主要”
          目的地分支：“紫野”
          github_token : ${{ secrets.PAT }}
